import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from '@next/font/google'
// import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'
import Article from '../components/Article'
import { createClient } from '../prismicio'
// const inter = Inter({ subsets: ['latin'] })
import { Bounded } from "../components/Bounded";
export default function Home({navigation, settings, articles}) {
  
  return (
    <>
      <Layout
        navigation={navigation}
        settings={settings}
      >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Bounded size="widest">
      <ul className="grid grid-cols-1 gap-16">
          {articles.map((article) => (
            <Article key={article.id} article={article} />
          ))}
        </ul>
        </Bounded>
      </Layout>
    </>
  )
}
export async function getStaticProps({ previewData }) {
  const client = createClient({ previewData });
  const articles = await client.getAllByType("article");
  const navigation = await client.getSingle("navigation");
  const settings = await client.getSingle("settings");
 
  return {
    props: { 
      navigation,
      settings,
      articles
    } 
  }
}